OUTPUT_DIR: "./output/pmtd"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: 'models/PMTD_ICDAR2017MLT.pth'
#  WEIGHT: "r50_imagenet_pretrained.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    STEM_FUNC: "StemWithBatchNorm"
    TRANS_FUNC: "BottleneckWithBatchNorm"
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
#  RESNETS:
#    BACKBONE_OUT_CHANNELS: 256
  RPN:
    RPN_HEAD: "SingleConvRPNHead_Softmax"
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ASPECT_RATIOS: (0.17, 0.44, 1.13, 2.90, 7.46)
    STRADDLE_THRESH: 10
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_PER_BATCH: False
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor_Upsample"
    DILATION: 2
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
PROCESS:
  PNMS: False
  NMS_THRESH: 0.2
DATASETS:
  TRAIN: ("ic17_train",)
  TEST: ("ic17_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.0001
  STEPS: (10000, 15000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 2500
INPUT:
  TO_BGR255: False
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
#  MIN_SIZE_TRAIN: 800
#  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: -1
  MAX_SIZE_TEST: 1600
#  CROP_PROB_TRAIN: 0.0
#  ROTATE_PROB_TRAIN: 0.0
#  ROTATE_DEGREE: 15
TEST:
  IMS_PER_BATCH: 4