OUTPUT_DIR: "./output/r50_baseline"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "r50_imagenet_pretrained.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.25, 0.5, 1.0, 2.0, 4.0)
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.05
    NMS: 0.5
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  MASK_ON: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  # BDN KE
  KE_ON: True
  ROI_KE_HEAD:
    FEATURE_EXTRACTOR: "KERCNNFPNFeatureExtractor"
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    PREDICTOR: "KERCNNC4Predictor"
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
    NUM_KES: 8
    KE_WEIGHT: 0.1
    MTY_WEIGHT: 0.01
    POSTPROCESS_KES: True # Must be true 
    RESCORING: False
    RESCORING_GAMA: 1.4 # [0,2]
PROCESS:
  PNMS: False
  NMS_THRESH: 0.2
DATASETS:
  TRAIN: ("ic15_train", )
  TEST: ("ic15_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.0001
  STEPS: (10000, 15000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 2500
INPUT:
  MIN_SIZE_TRAIN: (680,720,760,800,840,880,920,960,1000)
  MAX_SIZE_TRAIN: 1480
  MIN_SIZE_TEST:  1200
  MAX_SIZE_TEST: 1600
  CROP_PROB_TRAIN: 0.0 
  ROTATE_PROB_TRAIN: 0.0
  ROTATE_DEGREE: 15
TEST:
  IMS_PER_BATCH: 3

